version: '3.9'

services:
  service-backend:
    restart: on-failure
    container_name: "couponearapp"
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: "jdbc:mysql://mysqldb:3306/couponeardockerdb?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false" 
    depends_on:
      - mysqldb 

  mysqldb:
    stdin_open: true
    container_name: "couponearsql"
    image: mysql
    ports: 
      - "3306:3306"
    volumes:
      - ./db/:/data/db
    
    build:
      dockerfile: DBDockerfile
      context: .

    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=couponeardockerdb
      - MYSQL_PASSWORD=rootpass


