spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/couponeardb
    username: root
    password: rootpass
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  rabbitmq:
#    host: rabbitmq-exam.rmq3.cloudamqp.com
#    virtual-host: mxifnklj
#    username: student
#    password: XYR4yqc.cxh4zug6vje

  rabbitmq:
    host: localhost
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

appset:
  totalcampaings: 10
  totalcards: 200
  totalusercards: 10

