spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/couponeardb
    username: root
    password: rootpass
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: true
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

appset:
  totalcampaings: 10
  totalcards: 200